name: Say Hello!
on:
  issues:
    types: [opened, edited]
  schedule: 
    - cron: "*/5 * * * *"
  workflow_dispatch:
  

jobs:
  Close-Invalid-Issues:
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v7
        with:
          script: echo 'Hello, whomever you are!'
